DROP TABLE IF EXISTS T_EMPLOYEE;

CREATE TABLE T_EMPLOYEE(
  ID VARCHAR(50) PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  MIDDLE_INITIAL VARCHAR(100) ,
  LAST_NAME VARCHAR(100) NOT NULL,
  DOB VARCHAR(10) NOT NULL,
  DATE_EMPLOYMENT VARCHAR(10) NOT NULL,
  STATUS VARCHAR(10) NOT NULL
);